### PR TITLE
Fix failing multiline test

### PR DESCRIPTION
**Pull request by nbrew**
Added `waitsForPromise -> activationPromise` in both tests.
Moved editor insertText and command dispatch into `it` blocks.

Not as DRY but both tests pass.

### CODE REVIEW

**Comment by carlosbaraza** [comment]
Wow, thank you for the fix! Tomorrow I do the merge.

**Comment by carlosbaraza** [comment]
Hi @nbrew ,

The specs are passing in my machine. I can not actually understand why they are not in yours. It might be just because the `waitsForPromise -> activationPromise`?

Could we just keep the same spec structure adding the `waitsForPromise -> activationPromise` in the beforeEachs under each of the describes?

Note for myself: I should research a little about how to set up a CI build for Atom packages.

Thank you and kind regards,
Carlos.

**Comment by carlosbaraza** [comment]
Hi @nbrew ,

I added Travis CI to the repository. Could you merge that into your fork to checkout if it pass the CI build?

Thank you!
Carlos.

**Comment by nbrew** [comment]
Carlos,
Sorry for the confusion here. I suspect this issue has to do with the asynchronous execution of the specs. Or it is entirely possible that the failure I'm seeing may be related to how I'm running the tests. (I'm new to both coffeescript and atom plugins so I'm sure that doesn't help clarify matters.) 
- If I do a clone of yard:master and run `apm test` with no modifications the second test fails. Travis fails as well.
- If I apply this particularly ugly and unstructured chunk, both tests pass with apm and travis.

I'll see if I can retain more of your original structure and achieve passing tests.
Nathan

**Comment by nbrew** [comment]
Hi @carlosbaraza.

First off, thanks for adding Travis support! Secondly, here is what should have been submitted as a pull request in the first place. Six lines added having only to do with waiting for activation yielding passing tests.

I hope this is helpful.

Nathan

**Comment by carlosbaraza** [comment]
Hi @nbrew,

Great! That feels better and travis is happy about your modifications! I will then proceed with the merge.

Thank you very much for the fix,
Carlos.

**Pull request merged**
